name: Release

run-name: Release (${{ inputs.bump }}) from ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Version bump type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch

permissions:
  contents: write

jobs:
  release-package:
    uses: otfabric/.github/.github/workflows/go-package-release.yml@v2
    with:
      bump: ${{ inputs.bump }}
      release-name-prefix: go-otfp
      update-major-tag: false
    secrets: inherit

  release-otprobe-binary:
    needs: release-package
    uses: otfabric/.github/.github/workflows/go-binary-release.yml@v2
    with:
      bump: none
      binary-name: otprobe
      main-path: ./cmd/otprobe
      ldflags: "-s -w -X main.version=${VERSION} -X main.tag=${TAG} -X main.commit=${COMMIT} -X main.buildDate=${BUILD_DATE}"
      run-tests: false
    secrets: inherit